name: cradle
version: 0.0.0.0

dependencies:
  - base
  - bytestring
  - process
  - string-conversions
  - text

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -threaded

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -fdefer-typed-holes
    dependencies:
      - directory
      - filepath
      - hspec
      - hspec-discover
      - interpolate
      - mockery
      - silently
      - transformers
  readme:
    main: README.lhs
    dependencies:
      - cradle
      - markdown-unlit
    ghc-options:
      - -pgmL markdown-unlit

library:
  source-dirs:
    - src
